### PR TITLE
adding subgraph indexer and query on client, guest mode

### PR DESCRIPTION
**Pull request by Salmandabbakuti**
added: query video list, filter using subgraph on client
updated: include contract artifacts, indexer deployment steps
added: guest mode to browse videos without sign in(since subgraph query returns data without calling contract)

subgraph url: https://thegraph.com/hosted-service/subgraph/salmandabbakuti/ourtube
App in action: https://decentralized-you-tube.vercel.app/

### CODE REVIEW

**Comment by suhailkakar** [comment]
Great PR!!!

Going to review it and let you know :)

Thanks!

**Comment by Salmandabbakuti** [comment]
Thanks. Pls review guest mode as well :)

**Comment by suhailkakar** [comment]
Thanks!

btw, I am doing to deploy subgraphs to a separate account and update the URLs, because I am going to change a few parts in future. 

Hope that is not a problem!!

**Comment by Salmandabbakuti** [comment]
Sure no problem

**Comment by Salmandabbakuti** [comment]
May I know the status of your review? pls, let me know if anything needs to be taken care of?

**Comment by suhailkakar** [comment]
Merge :)

**Pull request merged**
